/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.categoria;
import controlador.estado;
import controlador.producto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pancho-PC
 */
public class MantenedorProductos extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    static producto p = new producto();
    producto pp = new producto();
    ArrayList<producto> apro = new ArrayList();
    ArrayList<categoria> cc = new ArrayList();
    categoria c = new categoria();

    /**
     * Creates new form MantenedorProductos
     */
    public MantenedorProductos() {
        initComponents();
        this.panelCampos.setVisible(false);
        modelo.addColumn("codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Valor");
        modelo.addColumn("Categoria");
        modelo.addColumn("Estado");
        this.tablaTranajador.setModel(modelo);
        p.cargarProductos(apro);
        c.cargarCategorias(cc);
        cargarTabla();
        ComboCategoria();
    }

    public void ComboCategoria() {
        if (!cc.isEmpty()) {
            for (categoria cat : cc) {
                this.ComboCategoria.addItem(cat.getCodigo() + ") " + cat.getDetalle());
            }
        } else {
            String[] a = new String[1];
            a[0] = "no existen categorias Disponibles";
            modelo.addRow(a);
        }
    }

    public void cargarTabla() {
        if (!apro.isEmpty()) {
            if (!this.checkInactivosTabla.isSelected()) {
                for (producto tr : apro) {
                    String[] a = new String[5];
                    if (tr.getEstado().getCodigo() == 1) {
                        a[0] = tr.getCodigo() + "";
                        a[1] = tr.getDetalle();
                        a[2] = tr.getValor() + "";
                        a[3] = tr.getCategoria().getDetalle();
                        a[4] = tr.getEstado().getDetalle();
                        modelo.addRow(a);
                    }
                }
            } else {
                for (producto tr : apro) {
                    String[] a = new String[5];
                    a[0] = tr.getCodigo() + "";
                    a[1] = tr.getDetalle();
                    a[2] = tr.getValor() + "";
                    a[3] = tr.getCategoria().getDetalle();
                    a[4] = tr.getEstado().getDetalle();
                    modelo.addRow(a);
                }
            }
        } else {
            String[] a = new String[1];
            a[0] = "no existen Productos Para Mostrar";
            modelo.addRow(a);
        }
    }

    public void limpiar() {
        this.txt_Codigo.setText("");
        this.txt_descripcion.setText("");
        this.txt_Valor.setText("");
        this.checkActivo.setSelected(false);
        this.checkInactivoEstado.setSelected(false);
        this.ComboCategoria.setSelectedIndex(0);
    }

    public void limpiarTabla() {
        for (int i = 0; i < this.tablaTranajador.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    public boolean camposNull() {
        if (!(this.txt_Valor.getText().equals("") || this.txt_descripcion.getText().equals(""))) {
            if (!(this.txt_Valor.getText().substring(0, 1).equals(" ") || this.txt_descripcion.getText().substring(0, 1).equals(" "))) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        checkInactivosTabla = new javax.swing.JCheckBox();
        BotonEliminar = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();
        BotonIKngresar = new javax.swing.JButton();
        panelCampos = new javax.swing.JPanel();
        txt_Codigo = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_Valor = new javax.swing.JTextField();
        checkActivo = new javax.swing.JCheckBox();
        checkInactivoEstado = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ComboCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTranajador = new javax.swing.JTable();

        setBorder(null);
        setTitle("Administracion de Productos");

        checkInactivosTabla.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkInactivosTabla.setText("Ver Inactivos");
        checkInactivosTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkInactivosTablaMouseClicked(evt);
            }
        });
        checkInactivosTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInactivosTablaActionPerformed(evt);
            }
        });

        BotonEliminar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BotonEliminar.setText("Activar/Desactivar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonEditar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BotonEditar.setText("Editar");
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        BotonIKngresar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BotonIKngresar.setText("Ingresar");
        BotonIKngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIKngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(checkInactivosTabla))
                    .addComponent(BotonIKngresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(checkInactivosTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(BotonIKngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        panelCampos.setMaximumSize(new java.awt.Dimension(908, 280));

        txt_Codigo.setEditable(false);
        txt_Codigo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txt_descripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });

        txt_Valor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        buttonGroup1.add(checkActivo);
        checkActivo.setText("Activo");

        buttonGroup1.add(checkInactivoEstado);
        checkInactivoEstado.setText("Inactivo");

        jLabel1.setText("codigo");

        jLabel2.setText("Descripcion:");

        jLabel3.setText("Valor:");

        jLabel5.setText("Categoria:");

        labelEstado.setText("Estado:");

        botonGuardar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCamposLayout = new javax.swing.GroupLayout(panelCampos);
        panelCampos.setLayout(panelCamposLayout);
        panelCamposLayout.setHorizontalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamposLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(ComboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(labelEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3))
                    .addComponent(checkActivo)
                    .addComponent(checkInactivoEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panelCamposLayout.setVerticalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(ComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkActivo)
                        .addComponent(labelEstado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkInactivoEstado)
                .addGap(37, 37, 37)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        tablaTranajador = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){

                return false;

            }
        };
        tablaTranajador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaTranajador.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaTranajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTranajadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTranajador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkInactivosTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInactivosTablaActionPerformed
        limpiarTabla();
        cargarTabla();
    }//GEN-LAST:event_checkInactivosTablaActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        int fila = this.tablaTranajador.getSelectedRow();
        if (fila >= 0) {
            int codigo = Integer.parseInt(this.tablaTranajador.getValueAt(fila, 0).toString());
            JOptionPane.showMessageDialog(null, p.CambiarEstado(codigo));
            limpiar();
            limpiarTabla();
            apro.removeAll(apro);
            p.cargarProductos(apro);
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto para desactivar");
        }
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        if(this.tablaTranajador.getSelectedRow() >= 0){
        try {
            this.jButton1.setVisible(false);
            this.botonGuardar.setVisible(true);
            this.panelCampos.setVisible(true);
            this.BotonIKngresar.setVisible(false);
            this.BotonEditar.setVisible(false);
            this.BotonEliminar.setVisible(false);
            this.checkActivo.setVisible(true);
            this.checkInactivoEstado.setVisible(true);
            this.labelEstado.setVisible(true);
            this.txt_Codigo.setEditable(false);
            int fila = this.tablaTranajador.getSelectedRow();
            int cod = Integer.parseInt(this.tablaTranajador.getValueAt(fila, 0).toString());
            for (producto a : apro) {
                if (a.getCodigo() == cod) {
                    this.txt_Codigo.setText(a.getCodigo() + "");
                    this.txt_descripcion.setText(a.getDetalle());
                    this.txt_Valor.setText(a.getValor() + "");
                    this.ComboCategoria.setSelectedIndex((a.getCategoria().getCodigo()) - 1);
                    if (a.getEstado().getCodigo() == 1) {
                        this.checkActivo.setSelected(true);
                    } else {
                        this.checkInactivoEstado.setSelected(true);
                    }
                    break;
                }
            }
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "seleccione un producto antes de editar");
        }
        }else{
            JOptionPane.showMessageDialog(null, "seleccione un producto antes de editar");
        }
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonIKngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIKngresarActionPerformed
        this.jButton1.setVisible(true);
        this.botonGuardar.setVisible(false);
        this.panelCampos.setVisible(true);
        this.BotonIKngresar.setVisible(false);
        this.BotonEditar.setVisible(false);
        this.BotonEliminar.setVisible(false);
        this.checkActivo.setVisible(false);
        this.checkInactivoEstado.setVisible(false);
        this.labelEstado.setVisible(false);
        this.txt_Codigo.setEditable(false);
        limpiar();
    }//GEN-LAST:event_BotonIKngresarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if (camposNull()) {
            try {
                pp.setCodigo(Integer.parseInt(this.txt_Codigo.getText()));
                pp.setDetalle(this.txt_descripcion.getText());
                pp.setValor(Integer.parseInt(this.txt_Valor.getText()));
                if (this.checkActivo.isSelected()) {
                    pp.setEstado(new estado(1, "activo"));
                } else {
                    pp.setEstado(new estado(2, "Inactivo"));
                }
                int codcat = Integer.parseInt(this.ComboCategoria.getSelectedItem().toString().substring(0, 1));
                pp.setCategoria(new categoria(codcat, "Categoria"));
                JOptionPane.showMessageDialog(null, p.ActualizarProducto(pp));
                limpiar();
                limpiarTabla();
                apro.removeAll(apro);
                p.cargarProductos(apro);
                cargarTabla();
                this.panelCampos.setVisible(false);
                this.BotonIKngresar.setVisible(true);
                this.BotonEliminar.setVisible(true);
                this.BotonEditar.setVisible(true);
            } catch (java.lang.NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El campo 'Valor' deve ser numerico ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos Los Campos Son Obligatorios");
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.panelCampos.setVisible(false);
        this.BotonEliminar.setVisible(true);
        this.BotonIKngresar.setVisible(true);
        this.BotonEditar.setVisible(true);
        limpiar();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (camposNull()) {
            try {
                pp.setDetalle(this.txt_descripcion.getText());
                pp.setValor(Integer.parseInt(this.txt_Valor.getText()));
                pp.setEstado(new estado(1, "activo"));
                int codcat = Integer.parseInt(this.ComboCategoria.getSelectedItem().toString().substring(0, 1));
                pp.setCategoria(new categoria(codcat, "Categoria"));
                JOptionPane.showMessageDialog(null, p.ingresarProducto(pp));
                limpiar();
                limpiarTabla();
                apro.removeAll(apro);
                p.cargarProductos(apro);
                cargarTabla();
            } catch (java.lang.NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El campo 'Valor' deve ser numerico ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos Los Campos Son Obligatorios");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaTranajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTranajadorMouseClicked

    }//GEN-LAST:event_tablaTranajadorMouseClicked

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void checkInactivosTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInactivosTablaMouseClicked

    }//GEN-LAST:event_checkInactivosTablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonIKngresar;
    private javax.swing.JComboBox<String> ComboCategoria;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkActivo;
    private javax.swing.JCheckBox checkInactivoEstado;
    private javax.swing.JCheckBox checkInactivosTabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JTable tablaTranajador;
    private javax.swing.JTextField txt_Codigo;
    private javax.swing.JTextField txt_Valor;
    private javax.swing.JTextField txt_descripcion;
    // End of variables declaration//GEN-END:variables
}
