/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Confi.ColorearFilas;
import controlador.categoria;
import controlador.producto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pancho-PC
 */
public class VerProductosVendedor extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    static producto p = new producto();
    static categoria c = new categoria();
    ArrayList<producto> Apro = new ArrayList();
    ArrayList<categoria> Aca = new ArrayList();
    ArrayList<ArrayList<String>> Stock = new ArrayList();
    ColorearFilas colorear = new ColorearFilas();

    /**
     * Creates new form VerProductosVendedor
     */
    public VerProductosVendedor() {
        initComponents();
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Valor");
        modelo.addColumn("Categoria");
        modelo.addColumn("Stock");
        this.tableProductos.setModel(modelo);
        p.cargarProductos(Apro);
        p.StockProductos(Stock);
        c.cargarCategorias(Aca);
        CargarTabla();
        cargarComboCategoria();
        this.tableProductos.setDefaultRenderer(Object.class, colorear);
    }

    public void CargarTabla() {
        if (!Apro.isEmpty()) {
            for (producto pr : Apro) {
                String[] a = new String[5];
                if (pr.getEstado().getCodigo() == 1) {
                    a[0] = pr.getCodigo() + "";
                    a[1] = pr.getDetalle();
                    a[2] = pr.getValor() + "";
                    a[3] = pr.getCategoria().getDetalle();
                    a[4] = "0";
                    modelo.addRow(a);
                }
            }
            StockProductos();
        } else {
            String[] men = new String[1];
            men[0] = "no existen productos para mostrar";
            modelo.addRow(men);
        }
    }

    public void cargarComboCategoria() {
        this.Combocategoria.addItem("<Ninguna>");
        if (!Aca.isEmpty()) {
            for (categoria ct : Aca) {
                this.Combocategoria.addItem(ct.getDetalle());
            }
        }
    }

    public void limpiarTabla() {
        for (int i = 0; i < this.tableProductos.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    public void StockProductos() {
        int filas = this.tableProductos.getRowCount();
        for (ArrayList<String> st : Stock) {
            for (int i = 0; i < filas; i++) {
                if (this.tableProductos.getValueAt(i, 0).toString().equals(st.get(0))) {
                    this.tableProductos.setValueAt(st.get(1), i, 4);
                    break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        Combocategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();

        setBorder(null);
        setTitle("Productos Disponibles");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Buscar Producto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        txtBusqueda.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        Combocategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombocategoriaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Categoria :");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Busqueda :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Combocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Combocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        tableProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tableProductos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableProductos.getTableHeader().setReorderingAllowed(false);
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableProductosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        Apro.removeAll(Apro);
        p.buscarProducto(Apro, this.txtBusqueda.getText());
        limpiarTabla();
        for (producto busq : Apro) {
            String[] z = new String[5];
            z[0] = busq.getCodigo() + "";
            z[1] = busq.getDetalle();
            z[2] = busq.getValor() + "";
            z[3] = busq.getCategoria().getDetalle() + "";
            z[4] = "0";
            modelo.addRow(z);
        }
        this.tableProductos.setModel(modelo);
        StockProductos();
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void CombocategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombocategoriaActionPerformed
        if (this.Combocategoria.getSelectedIndex() != 0) {
            limpiarTabla();
            for (producto catp : Apro) {
                if (catp.getCategoria().getCodigo() == this.Combocategoria.getSelectedIndex()) {
                    String[] z = new String[5];
                    z[0] = catp.getCodigo() + "";
                    z[1] = catp.getDetalle();
                    z[2] = catp.getValor() + "";
                    z[3] = catp.getCategoria().getDetalle() + "";
                    z[4] = "0";
                    modelo.addRow(z);
                }
            }
            this.tableProductos.setModel(modelo);
            StockProductos();
        } else {
            limpiarTabla();
            CargarTabla();
        }

    }//GEN-LAST:event_CombocategoriaActionPerformed

    private void tableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableProductosMouseClicked

    private void tableProductosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseReleased

    }//GEN-LAST:event_tableProductosMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combocategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
